---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/US
      - VERSION=public
    volumes:
      - /appdata/plex/library:/config
      - /media/lost-bag-usb/music:/music
    restart: unless-stopped