---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=http://192.168.0.5 
    volumes:
      - /appdata/jellyfin/library:/config
      - /media/lost-bag-usb/music:/data/music
    ports:
      - 8096:8096al
    restart: unless-stopped