---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/US
    volumes:
      - /appdata/jellyfin/library:/config
      - /media/lost-bag-usb/music:/data/music
    ports:
      - 8096:8096
    restart: unless-stopped
