---
# services:
#   jellyfin:
#     image: lscr.io/linuxserver/jellyfin:latest
#     container_name: jellyfin
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - TZ=Etc/US
#       - JELLYFIN_PublishedServerUrl=http://192.168.0.5 
#     volumes:
#       - /appdata/jellyfin/library:/config
#       - /media/lost-bag-usb/music:/data/music
#     ports:
#       - 8096:8096
#     restart: unless-stopped
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: 'host'
    volumes:
      - /appdata/jellyfin/library:/config
      - /appdata/jellying/cache:/cache
      - type: bind
        source: media/lost-bag-usb/music
        target: /music
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://lostbag.server
